#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys


def setup_config():
    if not os.path.exists('config.json'):
        raise ValueError('Cannot find config.json file')

    import json
    from vtserver import settings

    config = json.load(open('config.json', 'r'))

    if 'SECRET_KEY' not in config:
        raise ValueError('Cannot find "SECRET_KEY" value in the "config.json" file. '
                         'It should be generated by django and put here')

    settings.SECRET_KEY = config['SECRET_KEY']


def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'vtserver.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
